crdroid-a71:
  kernel:
    - git clone https://github.com/crdroidandroid/android_kernel_samsung_a71.git -b 16.0
  clang:
    - git clone --depth=1 https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 -b main-kernel clang
  config:
    - make O=out ARCH=arm64 a71_defconfig
  build:
    - ARCH=arm64 CROSS_COMPILE="${PWD}/clang/bin/aarch64-linux-gnu-" CROSS_COMPILE_COMPAT="${PWD}/clang/bin/arm-linux-gnueabi-" CLANG_TRIPLE=aarch64-linux-gnu- make -j$(nproc --all) LLVM=1 LLVM_IAS=1 O=out CC="${PWD}/clang/clang-stable/bin/clang"
  target:
    - out/arch/arm64/boot/Image.gz-dtb
  anykernel:
    - nashc
  kernelSU:
    - stable-pin
    
